# Generated by Django 3.1.3 on 2020-11-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='number',
        ),
    ]
